# Generated by Django 5.1.7 on 2025-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=20)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
            ],
        ),
    ]
