# Generated by Django 5.1.7 on 2025-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
